#ifndef LIBAVIAWIDGETS_GLOBAL_H
#define LIBAVIAWIDGETS_GLOBAL_H

#include <QtCore/qglobal.h>

#if defined(LIBAVIAWIDGETS_LIBRARY)
#  define LIBAVIAWIDGETSSHARED_EXPORT Q_DECL_EXPORT
#else
#  define LIBAVIAWIDGETSSHARED_EXPORT Q_DECL_IMPORT
#endif

#endif // LIBAVIAWIDGETS_GLOBAL_H
